# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

# Computer-generated files and other files which cannot be copyrighted
[[annotations]]
path = [
    ".ansible-lint",
    ".github/renovate.json",
    ".github/workflows/pre-commit.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".python-version",
    ".yamllint.yml",
    "LICENSE",
    "README.md",
    "meta/main.yml",
    "molecule/**/requirements.yml",
    "molecule/README.md",
    "molecule/requirements.txt",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
