# SPDX-FileCopyrightText: 2024 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install the tinc package
  ansible.builtin.package:
    name: tinc
    state: present
  notify: Restart Tinc
  tags: ansible-role-tinc

- name: Create the base tinc directory
  ansible.builtin.file:
    path: "{{ tinc_directory }}"
    state: directory
    mode: "0750"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
  notify: Restart Tinc
  tags: ansible-role-tinc

- name: Create the tinc network name directory
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.file:
    path: "{{ tinc_directory }}/{{ item.network_name }}"
    state: directory
    mode: "0750"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Create the tinc hosts directory
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.file:
    path: "{{ tinc_directory }}/{{ item.network_name }}/hosts"
    state: directory
    mode: "0750"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Write tinc.conf
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: tinc.conf.j2
    dest: "{{ tinc_directory }}/{{ item.network_name }}/tinc.conf"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0644"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Write tinc-up
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: tinc-up.j2
    dest: "{{ tinc_directory }}/{{ item.network_name }}/tinc-up"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0755"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Write tinc-down
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: tinc-down.j2
    dest: "{{ tinc_directory }}/{{ item.network_name }}/tinc-down"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0755"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Write RSA private key if defined
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: rsa_key.priv.j2
    dest: "{{ tinc_directory }}/{{ item.network_name }}/rsa_key.priv"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0600"
  notify: Restart Tinc
  when: item.rsa_private_key is defined
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Generate RSA private key if missing
  no_log: "{{ tinc_no_log }}"
  community.crypto.openssl_privatekey:
    path: "{{ tinc_directory }}/{{ item.network_name }}/rsa_key.priv"
    size: 4096
    type: RSA
    mode: "0600"
  loop: "{{ tinc_networks }}"
  when: item.rsa_private_key is not defined
  notify: Restart Tinc
  tags: ansible-role-tinc

- name: Extract RSA public key if missing
  no_log: "{{ tinc_no_log }}"
  community.crypto.openssl_publickey:
    path: "{{ tinc_directory }}/{{ item.network_name }}/rsa_key.pub"
    privatekey_path: "{{ tinc_directory }}/{{ item.network_name }}/rsa_key.priv"
  loop: "{{ tinc_networks }}"
  when: item.rsa_public_key is not defined
  register: rsa_public_key
  tags: ansible-role-tinc

- name: Read generated RSA public key for display
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.slurp:
    src: "{{ tinc_directory }}/{{ item.item.network_name }}/rsa_key.pub"
  loop: "{{ rsa_public_key.results }}"
  when: item.changed # noqa: no-handler
  register: rsa_public_key_content
  tags: ansible-role-tinc

- name: Print RSA public key if newly generated
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.debug:
    msg: "{{ item.content | b64decode }}"
  loop: "{{ rsa_public_key_content.results }}"
  when: item.content is defined
  tags: ansible-role-tinc

- name: Trigger role failure if public key needs to be recorded
  ansible.builtin.fail:
    msg: "Please add the generated RSA public key, printed above, to your tinc_networks variables and re-run"
  when: rsa_public_key.results | selectattr('changed') | list | length > 0
  tags: ansible-role-tinc

- name: Write a host file
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: host.j2
    dest: "{{ tinc_directory }}/{{ item.network_name }}/hosts/{{ item.host_name }}"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0644"
  notify: Restart Tinc
  loop: "{{ tinc_networks }}"
  tags: ansible-role-tinc

- name: Write more host files
  no_log: "{{ tinc_no_log }}"
  ansible.builtin.template:
    src: host.j2
    dest: "{{ tinc_directory }}/{{ item.0.network_name }}/hosts/{{ item.1.host_name }}"
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: "0644"
  notify: Restart Tinc
  loop: "{{ tinc_networks | subelements('hosts') }}"
  tags: ansible-role-tinc
